name: Example Backend CI

on:
  push:
  pull_request:

jobs:
  sast:
    uses: ./.github/workflows/sast-template.yml
    with:
      source_path: "."
      ruleset: "p/nodejs"

  policy:
    needs: sast
    uses: ./.github/workflows/sast-policy-enforcement.yml
